// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (clerk_invitation_id, email, inviter_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_invitation_id, email, inviter_id, status, created_at, accepted_at
`

type CreateInvitationParams struct {
	ClerkInvitationID string
	Email             string
	InviterID         uuid.UUID
	Status            InvitationStatus
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ClerkInvitationID,
		arg.Email,
		arg.InviterID,
		arg.Status,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.ClerkInvitationID,
		&i.Email,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const invitationsByInviter = `-- name: InvitationsByInviter :many
SELECT id, clerk_invitation_id, email, inviter_id, status, created_at, accepted_at FROM invitations
WHERE inviter_id = $1
ORDER BY created_at DESC
`

func (q *Queries) InvitationsByInviter(ctx context.Context, inviterID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, invitationsByInviter, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.ClerkInvitationID,
			&i.Email,
			&i.InviterID,
			&i.Status,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations
SET status = 'accepted', accepted_at = now()
WHERE lower(email) = lower($1::text)
  AND status = 'pending'
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, email)
	return err
}

const pendingInvitationByEmail = `-- name: PendingInvitationByEmail :one
SELECT id, clerk_invitation_id, email, inviter_id, status, created_at, accepted_at FROM invitations
WHERE lower(email) = lower($1::text)
  AND status = 'pending'
`

func (q *Queries) PendingInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, pendingInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.ClerkInvitationID,
		&i.Email,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}
