// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library_entries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLibraryEntry = `-- name: CreateLibraryEntry :one
INSERT INTO library_entries (
    member_id, work_id, status, progress, rating, is_favourite, owned, note, started_at, finished_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::library_status,
    $4::int,
    $5::int,
    $6::boolean,
    $7::boolean,
    $8::text,
    $9::timestamptz,
    $10::timestamptz
)
RETURNING id, member_id, work_id, status, progress, rating, is_favourite, owned, note, started_at, finished_at, created_at, updated_at
`

type CreateLibraryEntryParams struct {
	MemberID    uuid.UUID
	WorkID      uuid.UUID
	Status      LibraryStatus
	Progress    int32
	Rating      *int32
	IsFavourite bool
	Owned       bool
	Note        *string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

// Any of the six statuses is accepted: creating an entry is the entry point
// into the lifecycle, not a transition, so registering something you finished
// years ago does not have to travel through 'pending' first. The state machine
// constrains what comes after, and it lives in the service.
func (q *Queries) CreateLibraryEntry(ctx context.Context, arg CreateLibraryEntryParams) (LibraryEntry, error) {
	row := q.db.QueryRow(ctx, createLibraryEntry,
		arg.MemberID,
		arg.WorkID,
		arg.Status,
		arg.Progress,
		arg.Rating,
		arg.IsFavourite,
		arg.Owned,
		arg.Note,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WorkID,
		&i.Status,
		&i.Progress,
		&i.Rating,
		&i.IsFavourite,
		&i.Owned,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibraryEntry = `-- name: DeleteLibraryEntry :execrows
DELETE FROM library_entries WHERE id = $1::uuid
`

// Returns the number of rows removed so the adapter can answer "not found" on
// the second attempt instead of pretending a delete happened. Unscoped for the
// same reason the read is: library.EntryRepository.Delete takes an id, and
// RemoveFromLibrary has already resolved the owner through ownedEntry.
//
// The work itself is untouched: domain rule 3, it is shared history.
func (q *Queries) DeleteLibraryEntry(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLibraryEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const libraryEntryByID = `-- name: LibraryEntryByID :one
SELECT id, member_id, work_id, status, progress, rating, is_favourite, owned, note, started_at, finished_at, created_at, updated_at FROM library_entries WHERE id = $1::uuid
`

// Deliberately NOT scoped by member, and that is the one thing worth arguing
// about here. library.EntryRepository.ByID takes an id and nothing else,
// because the domain decided that "somebody else's entry answers as missing"
// is a rule of the service — Service.ownedEntry — rather than of the storage.
// Holding it in both places sounds safer and is not: the service would still
// have to compare the owner to tell 404 from 403, and a WHERE that can never
// fail is a branch no test can reach.
//
// The work does not travel with it either, for the same reason: the port
// answers an Entry. GetEntry therefore costs two statements, a constant two,
// which is a different thing from the N+1 the listing avoids.
func (q *Queries) LibraryEntryByID(ctx context.Context, id uuid.UUID) (LibraryEntry, error) {
	row := q.db.QueryRow(ctx, libraryEntryByID, id)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WorkID,
		&i.Status,
		&i.Progress,
		&i.Rating,
		&i.IsFavourite,
		&i.Owned,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const libraryEntryByMemberAndWork = `-- name: LibraryEntryByMemberAndWork :one
SELECT id, member_id, work_id, status, progress, rating, is_favourite, owned, note, started_at, finished_at, created_at, updated_at FROM library_entries
WHERE member_id = $1::uuid
  AND work_id = $2::uuid
`

type LibraryEntryByMemberAndWorkParams struct {
	MemberID uuid.UUID
	WorkID   uuid.UUID
}

// The read behind `409 already_in_library`. It is a convenience, not the
// guarantee: two concurrent requests both read "not there" and both insert, so
// what actually holds domain rule 1 is library_entries_member_work_idx. Treat
// the unique violation as the real answer and this as the fast path.
func (q *Queries) LibraryEntryByMemberAndWork(ctx context.Context, arg LibraryEntryByMemberAndWorkParams) (LibraryEntry, error) {
	row := q.db.QueryRow(ctx, libraryEntryByMemberAndWork, arg.MemberID, arg.WorkID)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WorkID,
		&i.Status,
		&i.Progress,
		&i.Rating,
		&i.IsFavourite,
		&i.Owned,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraryEntries = `-- name: ListLibraryEntries :many
SELECT le.id, le.member_id, le.work_id, le.status, le.progress, le.rating, le.is_favourite, le.owned, le.note, le.started_at, le.finished_at, le.created_at, le.updated_at, w.id, w.title, w.category, w.source, w.source_id, w.cover_url, w.synopsis, w.year, w.metadata, w.expansion_of, w.created_at, w.updated_at
FROM library_entries le
JOIN works w ON w.id = le.work_id
WHERE le.member_id = $1::uuid
  AND ($2::library_status IS NULL OR le.status = $2::library_status)
  AND ($3::work_category IS NULL OR w.category = $3::work_category)
  AND (
    $4::timestamptz IS NULL
    OR (le.created_at, le.id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY le.created_at DESC, le.id DESC
LIMIT $6::int
`

type ListLibraryEntriesParams struct {
	MemberID       uuid.UUID
	Status         *LibraryStatus
	Category       *WorkCategory
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *uuid.UUID
	PageLimit      int32
}

type ListLibraryEntriesRow struct {
	LibraryEntry LibraryEntry
	Work         Work
}

// The caller's own library, newest first, keyset-paginated
// (ADR-0011: docs/decisions/0011-paginacion-por-cursor.md). Pass a NULL
// after_created_at to fetch the first page. There is no separate wishlist
// query because the wishlist is not a separate thing: it is status='wishlist'
// arriving through this same filter.
//
// Unfiltered, the keyset walks library_entries_member_created_idx, which
// delivers (member_id, created_at DESC, id DESC) already ordered. With a
// status filter it walks library_entries_member_status_idx, which carries the
// same two ordering columns after (member_id, status) for exactly that reason:
// without them the planner ignored it entirely and filtered on top of the
// other index instead. The category filter reaches across the join into works,
// so it is applied there rather than pushed into either entry index.
//
// All of that holds for a custom plan: under a generic one the NULL guard
// blocks the row-comparison pushdown and Postgres sorts the partition instead,
// and the cost then grows with depth. Harmless at this size, but do not copy
// this comment elsewhere as a guarantee.
func (q *Queries) ListLibraryEntries(ctx context.Context, arg ListLibraryEntriesParams) ([]ListLibraryEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLibraryEntries,
		arg.MemberID,
		arg.Status,
		arg.Category,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryEntriesRow{}
	for rows.Next() {
		var i ListLibraryEntriesRow
		if err := rows.Scan(
			&i.LibraryEntry.ID,
			&i.LibraryEntry.MemberID,
			&i.LibraryEntry.WorkID,
			&i.LibraryEntry.Status,
			&i.LibraryEntry.Progress,
			&i.LibraryEntry.Rating,
			&i.LibraryEntry.IsFavourite,
			&i.LibraryEntry.Owned,
			&i.LibraryEntry.Note,
			&i.LibraryEntry.StartedAt,
			&i.LibraryEntry.FinishedAt,
			&i.LibraryEntry.CreatedAt,
			&i.LibraryEntry.UpdatedAt,
			&i.Work.ID,
			&i.Work.Title,
			&i.Work.Category,
			&i.Work.Source,
			&i.Work.SourceID,
			&i.Work.CoverUrl,
			&i.Work.Synopsis,
			&i.Work.Year,
			&i.Work.Metadata,
			&i.Work.ExpansionOf,
			&i.Work.CreatedAt,
			&i.Work.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibraryEntry = `-- name: UpdateLibraryEntry :one
UPDATE library_entries
SET status       = $1::library_status,
    progress     = $2::int,
    rating       = $3::int,
    is_favourite = $4::boolean,
    owned        = $5::boolean,
    note         = $6::text,
    started_at   = $7::timestamptz,
    finished_at  = $8::timestamptz,
    updated_at   = now()
WHERE id = $9::uuid
  AND member_id = $10::uuid
RETURNING id, member_id, work_id, status, progress, rating, is_favourite, owned, note, started_at, finished_at, created_at, updated_at
`

type UpdateLibraryEntryParams struct {
	Status      LibraryStatus
	Progress    int32
	Rating      *int32
	IsFavourite bool
	Owned       bool
	Note        *string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ID          uuid.UUID
	MemberID    uuid.UUID
}

// Every mutable column is written, so the service reads the entry, merges the
// patch and hands back the whole row. A COALESCE-per-column query cannot do
// this job: the contract distinguishes an absent property ("leave it") from an
// explicit null ("clear it"), and COALESCE collapses both into "leave it",
// which would make clearing a rating or a note impossible.
//
// work_id is absent by design: an entry never changes the work it points at.
// Scoped by member for the same reason the read is.
func (q *Queries) UpdateLibraryEntry(ctx context.Context, arg UpdateLibraryEntryParams) (LibraryEntry, error) {
	row := q.db.QueryRow(ctx, updateLibraryEntry,
		arg.Status,
		arg.Progress,
		arg.Rating,
		arg.IsFavourite,
		arg.Owned,
		arg.Note,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
		arg.MemberID,
	)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WorkID,
		&i.Status,
		&i.Progress,
		&i.Rating,
		&i.IsFavourite,
		&i.Owned,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
