// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteMemberByClerkID = `-- name: DeleteMemberByClerkID :exec
DELETE FROM members WHERE clerk_user_id = $1
`

func (q *Queries) DeleteMemberByClerkID(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, deleteMemberByClerkID, clerkUserID)
	return err
}

const memberByClerkID = `-- name: MemberByClerkID :one
SELECT id, clerk_user_id, username, display_name, avatar_url, email, invited_by, created_at, updated_at FROM members WHERE clerk_user_id = $1
`

func (q *Queries) MemberByClerkID(ctx context.Context, clerkUserID string) (Member, error) {
	row := q.db.QueryRow(ctx, memberByClerkID, clerkUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const memberByID = `-- name: MemberByID :one
SELECT id, clerk_user_id, username, display_name, avatar_url, email, invited_by, created_at, updated_at FROM members WHERE id = $1
`

func (q *Queries) MemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, memberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const memberExistsByEmail = `-- name: MemberExistsByEmail :one
SELECT EXISTS (
    SELECT 1 FROM members WHERE lower(email) = lower($1::text)
) AS member_exists
`

func (q *Queries) MemberExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, memberExistsByEmail, email)
	var member_exists bool
	err := row.Scan(&member_exists)
	return member_exists, err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO members (clerk_user_id, username, display_name, avatar_url, email, invited_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (clerk_user_id) DO UPDATE
SET username     = EXCLUDED.username,
    display_name = EXCLUDED.display_name,
    avatar_url   = EXCLUDED.avatar_url,
    email        = EXCLUDED.email,
    updated_at   = now()
RETURNING id, clerk_user_id, username, display_name, avatar_url, email, invited_by, created_at, updated_at
`

type UpsertMemberParams struct {
	ClerkUserID string
	Username    string
	DisplayName string
	AvatarUrl   string
	Email       string
	InvitedBy   *uuid.UUID
}

// Keyed by clerk_user_id so a redelivered webhook refreshes the profile instead
// of creating a second member.
func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, upsertMember,
		arg.ClerkUserID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Email,
		arg.InvitedBy,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
