// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: works.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWork = `-- name: CreateWork :one
INSERT INTO works (title, category, source, source_id, cover_url, synopsis, year, metadata)
VALUES (
    $1::text,
    $2::work_category,
    'manual',
    NULL,
    $3::text,
    $4::text,
    $5::int,
    -- COALESCE, not a bare argument: the contract makes metadata optional on
    -- CreateWorkRequest, and a required jsonb parameter would send Go's nil as
    -- SQL NULL and hit the NOT NULL constraint. A POST that simply omits the
    -- field has to land on the column's own '{}' default, not on a 500.
    COALESCE($6::jsonb, '{}')
)
RETURNING id, title, category, source, source_id, cover_url, synopsis, year, metadata, expansion_of, created_at, updated_at
`

type CreateWorkParams struct {
	Title    string
	Category WorkCategory
	CoverUrl *string
	Synopsis *string
	Year     *int32
	Metadata []byte
}

// Manual entry only, and the query is where that is enforced rather than in a
// handler: `source` and `source_id` are written here, not taken from the
// caller, so nothing can claim a record came from AniList when nobody checked.
// A manual work has no external record to point at, so source_id stays NULL,
// which is also what keeps it out of works_source_idx: manual works are
// deliberately not deduplicated.
func (q *Queries) CreateWork(ctx context.Context, arg CreateWorkParams) (Work, error) {
	row := q.db.QueryRow(ctx, createWork,
		arg.Title,
		arg.Category,
		arg.CoverUrl,
		arg.Synopsis,
		arg.Year,
		arg.Metadata,
	)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Source,
		&i.SourceID,
		&i.CoverUrl,
		&i.Synopsis,
		&i.Year,
		&i.Metadata,
		&i.ExpansionOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorks = `-- name: ListWorks :many
SELECT id, title, category, source, source_id, cover_url, synopsis, year, metadata, expansion_of, created_at, updated_at FROM works
WHERE ($1::work_category IS NULL OR category = $1::work_category)
  AND (
    $2::text IS NULL
    OR immutable_unaccent(lower(title)) LIKE
       '%' || replace(replace(replace(
           immutable_unaccent(lower($2::text)),
       '\', '\\'), '%', '\%'), '_', '\_') || '%'
  )
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListWorksParams struct {
	Category       *WorkCategory
	Search         *string
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *uuid.UUID
	PageLimit      int32
}

// A page of the shared catalogue, newest first, keyset-paginated
// (ADR-0011: docs/decisions/0011-paginacion-por-cursor.md). Pass a NULL
// after_created_at to fetch the first page. Both filters are optional and
// combine with an AND; a NULL means "do not filter", never "match nothing".
//
// works_category_created_idx serves the category filter and the whole ORDER BY
// at once, which is why the index carries the id tiebreak the keyset needs.
// That holds for a custom plan: under a generic one the NULL guard blocks the
// row-comparison pushdown and Postgres sorts the partition instead, and the
// cost then grows with depth. Harmless at this size, but do not copy this
// comment elsewhere as a guarantee.
//
// The title search folds case and accents, so "pokemon" finds "Pokémon"
// (ADR-0015). Both sides go through immutable_unaccent(lower(...)), and the
// left-hand side is spelled exactly as works_title_search_idx indexes it,
// which is what lets the planner use the index instead of reading every row.
//
// LIKE rather than strpos, and this is the one place the query is not the
// obvious shape. A GIN trigram index only answers LIKE, ILIKE and the regex
// operators; strpos is invisible to it, so a strpos search would be correct
// and would scan the whole catalogue forever. The property strpos was
// protecting is kept by escaping instead: the term arrives from a query
// string, so a backslash, a % and a _ are turned into literals before they
// reach the pattern, and somebody searching for "100%" searches for a percent
// sign rather than writing a wildcard.
//
// Two orderings hold this up, and only one of them is visible at a glance:
//
//  1. The escaping WRAPS the folding — immutable_unaccent runs on the inside,
//     the replaces on the outside. It has to be this way round because
//     unaccent emits wildcards of its own: full-width ％ (U+FF05) folds to %,
//     U+FF3C folds to a backslash, U+FF3F to an underscore. Escape first and
//     fold second and the fold manufactures a live wildcard out of a term
//     that had none — a wildcard injection that no ASCII test would catch.
//  2. Inside the escaping, backslash first, or the escapes that the other two
//     replaces introduce get escaped all over again.
func (q *Queries) ListWorks(ctx context.Context, arg ListWorksParams) ([]Work, error) {
	rows, err := q.db.Query(ctx, listWorks,
		arg.Category,
		arg.Search,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Work{}
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Source,
			&i.SourceID,
			&i.CoverUrl,
			&i.Synopsis,
			&i.Year,
			&i.Metadata,
			&i.ExpansionOf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workByID = `-- name: WorkByID :one
SELECT id, title, category, source, source_id, cover_url, synopsis, year, metadata, expansion_of, created_at, updated_at FROM works WHERE id = $1
`

func (q *Queries) WorkByID(ctx context.Context, id uuid.UUID) (Work, error) {
	row := q.db.QueryRow(ctx, workByID, id)
	var i Work
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Source,
		&i.SourceID,
		&i.CoverUrl,
		&i.Synopsis,
		&i.Year,
		&i.Metadata,
		&i.ExpansionOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
